### ISSUE TITLE
Topology.elem_eval return type

### ISSUE THREAD

**Issue by TheBB** [nutils/nutils#300] opened 2018-03-21 16:40 UTC
Currently, the return value of `elem_eval` seems to be a list of arrays, one per element. It seems that this is basically an implementation detail, that this list shouldn't be interacted with except for passing to a plot function.

I propose that it be turned into a full-on ndarray, basically just the same structure that already exists except the first axis (which is now a list) is part of the array, and that this be documented as part of the API so that the user can rely on this. This is useful because it allows one to do arithmetic on what is essentially evaluated functions. For example (because this is exactly a problem I had), I can more easily pre-compute the maxima and minima of a number related functions so that I can synchrionize the color ranges across a number of plots.

**Comment by TheBB** [comment] 2018-03-21 16:46
Specifically, I'm talking about the behaviour when `separate=True`.

**Comment by gertjanvanzwieten** [comment] 2018-03-22 09:59
Though I agree, the issue is that we cannot rely on all elements evaluating to the same shape. For instance, a heterogeneous topology consisting of both triangles and quads (uncommon but technically possible) would result in mixed arrays of 3 and 4 points along the first axis when evaluating in the vertices. The best we can do (and IMO should do) is test for this inside elem_eval and return an array whenever possible. Values are already evaluated in a concatenated array so the change would amount to reshaping it rather than breaking it up in small pieces, a performance win if nothing else, plus it's fully backwards compatible while giving the possibility on the receiving end to optimize for this (common) situation.

**Comment by TheBB** [comment] 2018-03-22 10:59
Looks like some functions in *plot* also expects to be able to tell bulk data from mesh data by the type of the input, so something would have to be done about that.

**Comment by joostvanzwieten** [comment] 2018-06-26 13:28
This is resolved by the new `Topology.sample` method.

**Closed by joostvanzwieten** 2018-06-26 13:28 UTC
Labels: enhancement
