### ISSUE TITLE
reusing arrayfunc structure

### ISSUE THREAD

**Issue by gertjanvanzwieten** [nutils/nutils#29] opened 2014-07-01 13:19 UTC
Nutils is currently unable to reuse function trees such as occurring in Newton/Picard iterations or time stepping, where integrands have identical structure but coefficients are changing. Requires some thinking but it's an important potential for optimization.

**Comment by joostvanzwieten** [comment] 2016-06-09 14:15
Closed as duplicate of #121.

**Closed by joostvanzwieten** 2016-06-09 14:15 UTC
Labels: enhancement
