### ISSUE TITLE
Bug in integration of single trimmed element boundary

### ISSUE THREAD

**Issue by fritsdeprenter** [nutils/nutils#82] opened 2015-10-30 23:19 UTC
When a single trimmed element's boundary is integrated, the outcome is incorrect for small elements. Plotting the boundary and volume of the trimmed element seems to uncover what's happening. I think the figures generated by the attached file will make the problem very clear, otherwise call me!

Somehow I don't have permission to attach files... The code is pasted here:

```
#! /usr/bin/env python

from nutils import *

def main( nelems=32, theta_v=numpy.pi/200*numpy.array([1,16,22,25]), maxrefine=0 ):

  for theta_n in numpy.arange(theta_v.shape[0]):
    log.user('--------------------')
    log.user('domain',str(int(theta_n)),'of',theta_v.shape[0])
    theta = theta_v[theta_n]

    verts = numpy.linspace( -1, 1, 2*nelems+1 )
    domain, geom = mesh.rectilinear( [verts,verts] )
    Q = function.asarray([ [  numpy.cos(theta), -numpy.sin(theta)],
                           [  numpy.sin(theta),  numpy.cos(theta)] ])
    x ,y     = geom
    xi,gamma = (Q.T*geom[_,:]).sum(-1)
  
    domain = domain.trim( .5 - xi   , maxrefine=maxrefine, name = 'trimright' )
    domain = domain.trim( .5 + xi   , maxrefine=maxrefine, name = 'trimleft' )
    domain = domain.trim( .5 - gamma, maxrefine=maxrefine, name = 'trimtop' )
    domain = domain.trim( .5 + gamma, maxrefine=maxrefine, name = 'trimbottom' )
    domain.volume_check(geom)
  
    elem_dict = {}
  
    #Indexing boundary elements
    for belem in domain.boundary:
      etrans = belem.transform.lookup( domain.edict )
      ielem  = domain.edict[ etrans ]
      elem_dict.setdefault(ielem,[]).append( belem )
  
    #Loop over boundary elements
    for ielem, belems in log.iter( 'boundary element', elem_dict.items() ):
      velem = domain.elements[ielem]
  
      #Create local topology
      vdomain = topology.Topology( [velem] )
      bdomain = topology.Topology( belems )
  
      #Calculate centre of mass
      length = bdomain.integrate( 1., geometry=geom, ischeme='gauss1' )
      volume, centre_mass_vol = vdomain.integrate( [ 1., geom ], geometry=geom, ischeme='gauss1' )
      centre_mass = centre_mass_vol/volume
  
      if volume < 1e-6:
        log.user('----------')
        log.user('element',ielem)
        log.user('length',length)
        log.user('volume',volume)
        log.user('centre_mass',centre_mass)
        vol_coords, vals = vdomain.simplex.elem_eval( [geom, 1.], ischeme='bezier5', separate=True )
        bound_coords     = bdomain.simplex.elem_eval(  geom     , ischeme='bezier5', separate=True )
        with plot.PyPlot( 'theta_'+str(int(theta_n))+'_element_'+str(int(ielem)), ndigits=0 ) as plt:
          plt.mesh( vol_coords, vals, edgewidth=.1, triangulate = 'bezier')
          for line_n in numpy.arange(len(bound_coords)):
            plt.plot(bound_coords[line_n][:,0],bound_coords[line_n][:,1],c='k',linewidth=10)
          plt.axes().set_aspect('auto')
        log.user('----------')
    log.user('--------------------')

  return

util.run( main )
```

**Comment by gertjanvanzwieten** [comment] 2015-11-06 11:55
This appears to be no bug, rather unexpected trimming behaviour caused by midpoint rounding. Closing.

**Closed by gertjanvanzwieten** 2015-11-06 11:55 UTC
